spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sani_civil_aid_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:yx011215}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:sani-civil-aid-default-2026-secret-pass-key}
  expiration: ${JWT_EXPIRATION:86400000}
  remember-me-expiration: ${JWT_REMEMBER_ME_EXPIRATION:2592000000}

deepseek:
    api-key: sk-5f85e6bf6b794efda159511fd7417f4f
    api-url: https://api.deepseek.com/chat/completions
